# Generated by Django 2.2.1 on 2019-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start',
        ),
        migrations.AddField(
            model_name='project',
            name='codebase',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='moreinfo',
            field=models.TextField(blank=True),
        ),
    ]
