# Generated by Django 2.2.1 on 2019-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190519_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='resume_education',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='resume_experience',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='main.Skill'),
        ),
    ]
