# Generated by Django 2.2.1 on 2019-05-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190519_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='codebase',
        ),
    ]
