# Generated by Django 2.2.1 on 2019-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_codebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('imagepath', models.TextField(blank=True)),
                ('classes', models.TextField(blank=True)),
                ('institute', models.CharField(max_length=200)),
                ('start', models.DateTimeField(blank=True, verbose_name='Start Date')),
                ('end', models.DateTimeField(blank=True, verbose_name='End Date')),
                ('jobtitle', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Resume_Experience',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='resume_education',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='resume_education',
            name='end',
        ),
        migrations.RemoveField(
            model_name='resume_education',
            name='start',
        ),
    ]
